src/pages/other/announce/UpdateAnnounce.js
> 공지사항 수정 기존 데이터 안보이던 버그 수정
> 기존 큰 이미지 파일도 수정할 수 있도록 수정
=> fix #7 - [공지사항] 공지사항 수정 기존 데이터 안보이던 버그

src/apis/CommonAPI.js, src/apis/CommuteAPICalls.js, src/components/commutes/CommuteItem.js, src/components/commutes/CommuteListByMember.js, src/components/commutes/CommuteTime.js, src/css/commute/commute.css, src/modules/CommuteModule.js, src/pages/commute/RecordCommute.js, src/pages/commute/RecordCorrectionOfCommute.js
=> feat #2 - [출퇴근] 멤버 출퇴근 조회 기능

src/apis/CalendarAPICalls.js, src/modules/CalendarModule.js, src/pages/calendar/Calendar.jsx, src/pages/calendar/UpdateModal.js
> 캘린더에서 일정을 선택하면  수정 모달창이 열립니다.
> 해당 모달창에는 선택된 일정의 정보로 값이 세팅되어 있습니다.
> 수정 버튼을 누르면 서버로 요청을 보내 해당 일정에 대한 정보를 수정하고 db로부터 새로 조회하여 변경된 사항을 반영합니다.
=> feat #3 - [캘린더] 일정 수정

src/pages/calendar/Calendar.jsx, src/pages/calendar/Modal.js, src/pages/calendar/UpdateModal.js
> 일정에 대한 상세 조회 내용을 넣기 위해 이벤트 객체에 상세설명 속성을 추가하였습니다.
> 상세 설명을 보여주기 위해 Popover 기능을 활용해 해당 일정에 마우스를 호버하면 해당 일정에 대한 정보와 상세정보가 나오도록 구현했습니다.
=> feat #4 - [캘린더] 일정 상세 조회

src/apis/CalendarAPICalls.js, src/modules/CalendarModule.js, src/pages/calendar/Calendar.jsx, src/pages/calendar/UpdateModal.js
> 캘린더에서 일정을 선택하면 해당 일정의 id를 delete 요청 경로에 넣어서 삭제 요청을 보낼 수 있습니다.
> 삭제가 완료되면 일정을 새로 조회해와 변경사항을 화면에 반영합니다.
=> feat #5 - [캘린더] 일정 삭제

src/apis/NoteAPICalls.js, src/components/Sidebar.js, src/modules/NoteMudule.js, src/pages/announce/Announces.js, src/pages/note/ReceiveNoteList.js, src/pages/note/SendNoteList.js
> 쪽지 삭제여부 수정하는 것으로, 쪽지 삭제 기능을 구현하였습니다.
> 받은 편지 / 보낸 편지  별로 각각 작업 되며,
> 이슈 수정 + backend 코드도 함께 리팩토링 하였습니다.
=> Feat#2 [쪽지] - 쪽지 삭제 ( 수정 )

src/apis/CommonAPI.js, src/apis/CommuteAPICalls.js, src/components/commutes/CommuteItem.js, src/components/commutes/CommuteListByMember.js, src/components/commutes/CommuteTime.js, src/pages/commute/RecordCommute.js, src/pages/commute/RecordCorrectionOfCommute.js
멤버별 출퇴근 내역 조회 시, 실제 근로 시간, 잔여 근로 시간 조회 기능 추가
=> feat #2 - [출퇴근] 멤버별 출퇴근 내역 조회 시, 실제 근로 시간, 잔여 근로 시간 조회 기능 추가

src/apis/CommonAPI.js, src/apis/CommuteAPICalls.js, src/components/commutes/CommuteTime.js, src/modules/CommuteModule.js, src/pages/commute/RecordCommute.js
=> feat #5 - [출퇴근] 출근 시간 등록

src/components/commutes/CommuteTime.js, src/pages/commute/RecordCommute.js
=> fix #6 - [출퇴근] 출근 시간 등록 시, 날짜 오류

src/App.js, src/apis/LeaveAPICalls.js, src/apis/NoteAPICalls.js, src/components/Sidebar.js, src/modules/LeaveModule.js, src/modules/index.js, src/pages/leave/MyLeave.css, src/pages/leave/MyLeave.js, src/pages/leave/utill/leaveUtill.js
> 토큰에서 사번을 꺼내 memberId로 사용해 해당 사번과 관련된 휴가 신청 내역을 조회합니다.
> 해당 사번이 가진 부여 휴가 일수, 소진 휴가 일수, 잔여 휴가 일수를 계산해서 화면에 출력합니다.
> 각 컬럼을 클릭하면 해당 컬럼명과 정렬방향의 상태를 변경해 새로 조회해와 변경 상태를 반영합니다.
=> feat #1- [휴가] 나의 휴가 내역 조회

src/pages/leave/MyLeave.js, src/pages/leave/utill/leaveUtill.js
> 기존에 로딩 화면은 처음 데이터를 불러올 때만 표기되고 그 이후로는 로딩 화면이 표시되지 않아 모든 페이징 과정에서 응답을 통해 데이터를 받아오기 전까지 로딩 화면을 보여주는 기능을 구현하였습니다.
=> feat #2 - [휴가] 나의 휴가 내역 조회 리팩토링

src/apis/LeaveAPICalls.js, src/css/common.css, src/pages/leave/MyLeave.js, src/pages/leave/utill/leaveUtill.js
> content가 비어있다면 null을 반환시켜 비어있는 content로 map 함수를 실행시키지 못하게 하였습니다.
=> fix #3 - [휴가] 나의 휴가 내역 조회 로딩 기능 수정

package-lock.json, package.json, src/apis/ChattingAPICalls.js, src/apis/NoteAPICalls.js, src/components/Header.js, src/css/note/sendNoteForm.css, src/modules/NoteMudule.js, src/pages/note/ReceiveNoteList.js, src/pages/note/SendNoteForm.js, src/pages/note/SendNoteList.js
> 쪽지 발송 기능을 구현하면서, 멤버 전체 조회하는 API도 만들어두었습니다. 필요하신 분들은 가져다가 쓰시면 될 것 같습니다.
=> Feat#3 [쪽지] - 쪽지 발송 / 멤버 전체 리스트 조회 API

src/apis/ApprovalAPICalls.js, src/modules/ApprovalModule.js, src/pages/approval/SendApprovalList.js
=> Feat#1전자결재상신함조회

src/pages/Main.css, src/pages/Main.js
> 메인 화면에 주간 일정을 확인할 수 있는 캘린더를 추가하였습니다.
=> feat #1 - [메인] 주간 캘린더 추가

package-lock.json, package.json, src/apis/ChattingAPICalls.js, src/css/chatting/room.css, src/css/chatting/roomList.css, src/modules/CahttingModules.js, src/modules/index.js, src/pages/chatting/Room.js, src/pages/chatting/RoomList.js, src/pages/note/ReceiveNoteList.js, src/pages/note/SendNoteList.js
> 서버단과 연결하는 것까지 성공하였는데, 시큐리티는 조금 손 봐야할 것 같긴 합니다.
> 쪽지 삭제 후, 강제 리로딩 시킨 것을 변경된 값을 적용시켜 비동기로 화면이 보여지도록 이슈 수정하였습니다.
=> feat#2 - [채팅] 실시간 채팅 서버 연결 완료

src/App.js, src/apis/ApprovalAPI.js, src/apis/ApprovalAPICalls.js, src/components/Sidebar.js, src/components/approvals/ApprovalListComponent.js, src/modules/ApprovalModule.js, src/pages/approval/ApprovalList.js, src/pages/approval/SendApprovalList.js
=> feat#1 전자결재 상신함 조회

src/pages/calendar/Calendar.jsx, src/pages/leave/MyLeave.js, src/utils/CalendarUtil.js
> convertToUtc 함수를 휴가에서도 사용하게 되어 해당 함수를 Common.js로 이동하며 import 구문을 수정도 함께 진행하였습니다.
=> feat #8 - [캘린더] CalendarUtil.js 에 있던 convertToUtc 함수 CommonUtil.js로 이동

package-lock.json, src/apis/CommuteAPICalls.js, src/css/commute/commute.css, src/pages/commute/ClockInModal.js, src/pages/commute/RecordCommute.js
출퇴근 등록 시, 같은 날짜에 여러번 출퇴근 등록되는 이슈해결하였습니다.
=> fix #9 - [출퇴근] 출퇴근 등록 시, 같은 날짜에 여러번 출퇴근 등록되는 이슈

src/apis/LeaveAPICalls.js, src/pages/calendar/Calendar.jsx, src/pages/calendar/CalendarModal.js, src/pages/leave/MyLeave.js, src/utils/leaveUtil.js
> 휴가 신청 삭제 버튼을 누르면 신청된 휴가를 삭제할 수 있습니다.
=> feat #5 - [휴가] 휴가 신청 삭제

src/css/note/noteLists.css, src/pages/Main.js, src/pages/announce/AnnouceList.js, src/pages/note/ReceiveNoteList.js, src/pages/note/SendNoteList.js
> 쪽지 호버 시 튀어나온느 것 같은 css 추가
> 메인 공지사항 -> 더보기 누르면 공지사항 리스트로 이동
=> style #1 - [메인/쪽지/공지사항] css 수정

package-lock.json, package.json, src/apis/ChattingAPICalls.js, src/css/chatting/customButton.css, src/css/chatting/joinRoom.css, src/css/chatting/room.css, src/modules/CahttingModules.js, src/modules/index.js, src/pages/chatting/CustomButton.js, src/pages/chatting/JoinRoom.js, src/pages/chatting/Room.js, src/pages/chatting/RoomList.js, src/pages/openAPI/OpenAPI.js
> 방 생성과 동시에, 리스트를 업데이트하는 것 까지 완료하였습니다
> 방이 생성되면, 왼쪽 리스트에 한칸씩 늘어나게 되며, 추후 유저 프로필에 대해서는 보완 할 예정입니다
=> feat#3 - [채팅] 방 생성 완료

src/pages/note/ReceiveNoteList.js, src/pages/note/SendNoteList.js
=> Feat#5 [쪽지] - 쪽지 리스트 회원 별로 프사 + 이름 + 사번 보이도록 수정

src/App.js, src/apis/LeaveAPICalls.js, src/css/calendar/CalendarModal.css, src/css/leave/LeaveAccrual.css, src/css/leave/LeaveAccrualModal.css, src/css/leave/MyLeave.css, src/css/leave/MyLeaveModal.css, src/modules/LeaveModule.js, src/pages/calendar/CalendarModal.js, src/pages/calendar/CalendarUpdateModal.js, src/pages/leave/LeaveAccrual.js, src/pages/leave/LeaveAccrualModal.js, src/pages/leave/MyLeave.js, src/pages/leave/MyLeaveModal.js, src/utils/leaveUtil.js
> 휴가 발생 내역을 조회해옵니다.
> 발생 버튼을 누르면 휴가 발생 모달이 보여집니다.
> 휴가 발생 모달창에서 이름을 입력하면 해당 입력값이 포함된 이름을 조회해서 셀렉트박스에 조회된 값들의 사번, 부서, 이름을 보여줍니다.
> 셀렉트박스에서 선택시 사원 이름, 사번 값이 입력됩니다.
> 휴가 발생 시 모달창이 닫히고 페이지가 새로고침되어 변경사항을 반영합니다.
=> feat #6  - [휴가] 휴가 발생 관리

src/App.js, src/apis/LeaveAPICalls.js, src/components/Sidebar.js, src/pages/leave/Leaves.js, src/utils/leaveUtil.js
> 전체 구성원의 휴가 보유 정보를 조회할 수 있습니다.
=> feat #9 - [휴가] 휴가 보유 내역 조회

src/components/approvals/TinyEditor.js, src/pages/approval/ApprovalInsert.js
=> feat#3 전자결재 기안

src/apis/CommuteAPICalls.js, src/components/commutes/CorrectionItem.js, src/components/commutes/CorrectionManageItem.js, src/components/commutes/CorrectionUpdateModal.js, src/css/commute/commute.css, src/modules/CommuteModule.js, src/pages/commute/CommuteCorrectionManage.js, src/pages/commute/RecordCommute.js, src/pages/commute/RecordCorrectionOfCommute.js
멤버별 출퇴근 정정 내역 상세 조회 기능 완료하였습니다.
=> feat #13 - [출퇴근] 멤버별 출퇴근 정정 내역 상세 조회

src/components/approvals/SelectFormComponent.js, src/components/approvals/TinyEditor.js, src/pages/approval/ApprovalInsert.js
=> feat #3 전자결재 기안

src/apis/InsiteAPICalls.js, src/apis/NoteAPICalls.js, src/modules/InsiteModule.js, src/pages/announce/AnnouceList.js, src/pages/announce/InsertAnnounce.js, src/pages/insite/DepartInsite.js, src/pages/insite/Insite.js, src/pages/insite/LeaveInsite.js, src/pages/note/ReceiveNoteList.js, src/pages/note/SendNoteList.js
> 금일 휴가자
> 금일 출근자 
- 통계 완료했습니다
=> feat #1 - [통계] 금일 휴가자 / 금일 출근자 현황 통계

src/css/survey/SurveyModal.css, src/css/survey/surveyList.css, src/pages/survey/SurveyModal.js, src/utils/SurveyUtil.js
> 설문조사 목록에서 보이는 제목이 일정 길이를 초과하면 생략해서 보이도록 수정하였습니다.
> 설문조사 참여 시 제목 길이에 맞게 textarea의 높이가 변경되도록 수정하였습니다.
=> feat #2 - [수요조사] 수요조사 제목 관련 리팩토링 및  css 수정

src/pages/Main.js
> 헤더에서 로그아웃을 정상적으로 진행할 수 있게 되어 임시 로그아웃 버튼을 삭제하였습니다.
=> feat #2 - [메인] 임시 로그아웃 버튼 삭제

src/css/leave/Leaves.css, src/pages/leave/Leaves.js, src/utils/leaveUtil.js
> 기능을 명확히 구분될 수 있게 소진 일수는 빨간색, 잔여 일수는 파란색으로 표시되도록 css를 수정하였습니다.
=> feat #10 - [휴가] 휴가 보유 내역 css 수정

src/apis/LeaveAPICalls.js, src/pages/leave/LeaveAccrual.js, src/pages/leave/LeaveAccrualModal.js, src/pages/leave/LeaveProcessing.js, src/pages/leave/Leaves.js, src/pages/leave/MyLeave.js
> 다른 기능의 페이지로 이동 시  페이징 정보를 초기화 하도록 의존성 배열이 빈 배열인 useEffect 구문에 페이징 번호 0을 dispatch 하는 구문 추가
> LeaveAccrualModal useEffect에 조건 걸어서 무의미한 요청 차단
> 휴가를 조회하는 API 함수 호출 구문을 비동기로 실행되게 처리하였습니다.
=> feat #11, fix #3 - [휴가] useEffect 구문 및 조회 로직 리팩토링 , 페이징 문제 해결

src/components/approvals/ApproverModal.js, src/components/approvals/CancelModal.js, src/components/approvals/UserInfoComponent.js, src/css/approval/UserInfoComponent.module.css, src/css/approval/approverModal.css, src/css/approval/cancelModal.css, src/css/approval/insertApproval.css, src/pages/approval/ApprovalInsert.js
=> feat#4 전자결재 결재선 참조선 연결 및 조회

src/pages/leave/LeaveProcessing.js, src/pages/leave/MyLeave.js, src/utils/leaveUtil.js
> 휴가가 처리 되기 전이라면 신청을 삭제할 수 있는 버튼이 현출됩니다.
> 취소와 반려는 글자 그대로 현출됩니다.
> 승인의 경우 휴가 시작일이 현재 일자를 기준으로 하루 이내라면 승인이라는 글자가 현출됩니다.
> 휴가 시작일이 현재 일자를 기준으로 하루 이상이라면 취소 신청 버튼이 현출됩니다.
=> feat #12 - [휴가] 나의 휴가 관리 처리 상태 현출 로직 리팩토링

src/pages/leave/LeaveAccrual.js, src/pages/leave/LeaveAccrualModal.js, src/pages/leave/LeaveProcessing.js, src/pages/leave/LeaveProcessingModal.js, src/pages/leave/Leaves.js, src/pages/leave/MyLeave.js, src/pages/leave/MyLeaveModal.js
> 가독성 향상을 목적으로 삼항연산자와 단축평가 코드의 배치를 수정하였습니다.
=> feat #13 - [휴가] 가독성 향상을 위한 리팩토링

src/components/approvals/ApproverModal.js, src/components/approvals/SelectFormComponent.js, src/components/approvals/TinyEditor.js, src/components/approvals/UserInfoComponent.js, src/css/approval/ApprovalInsert.module.css, src/css/approval/ApprovalListComponent.module.css, src/css/approval/ApproverModal.module.css, src/css/approval/SelectFormComponent.module.css, src/css/approval/UserInfoComponent.module.css, src/pages/approval/ApprovalInsert.js
=> Fix#1전자결재기안 css 수정

src/apis/ApprovalAPI.js, src/components/approvals/ApproverModal.js, src/components/approvals/TinyEditor.js, src/components/approvals/UserInfoComponent.js, src/css/approval/ApprovalInsert.module.css, src/css/approval/ApproverModal.module.css, src/css/approval/UserInfoComponent.module.css, src/modules/ApprovalReducer.js, src/pages/approval/ApprovalInsert.js
=> feat#4 전자결재 기안 화면 구현 및 수정

src/apis/LeaveAPICalls.js, src/css/leave/LeaveAccrual.css, src/css/leave/LeaveProcessing.css, src/pages/leave/LeaveAccrual.js, src/pages/leave/LeaveProcessing.js, src/pages/leave/LeaveProcessingModal.js, src/pages/leave/Leaves.js, src/pages/leave/MyLeave.js, src/utils/leaveUtil.js
=> feat #14 - [휴가] 휴가 관련 리팩토링

.gitignore, public/index.html, src/apis/InsiteAPICalls.js, src/common/ApprovalCounts.js, src/common/ApproverCounts.js, src/common/ClockContainer.js, src/common/MyLeaveCounts.js, src/common/Weather.js, src/css/ApprovalCounts.css, src/css/ApproverCounts.css, src/css/ClockContainer.css, src/css/MyLeaveCounts.css, src/css/main.css, src/css/weather.css, src/modules/ApprovalReducer.js, src/modules/InsiteModule.js, src/pages/Main.js, src/pages/note/SendNoteForm.js
현재 시간 (시계)
현재 위치 날씨
미승인 / 미처리 전자결재
본인 남은 휴가 일수
=> feat #3 - [메인] 메인 카드 4개 추가

src/apis/CalendarAPICalls.js, src/css/calendar/Calendar.css, src/pages/calendar/Calendar.js, src/pages/calendar/CalendarModal.js, src/pages/calendar/CalendarUpdateModal.js, src/pages/leave/Leaves.js, src/utils/CalendarUtil.js, src/utils/leaveUtil.js
> 부서 셀렉트박스를 추가하였습니다.
> 첫 렌더링 시에는 본인의 부서가 셀렉트박스에 표기됩니다.
> 부서를 클릭해 각 부서별 일저을 조회해올 수 있습니다.
> 일정 등록 시 요청에 포함되는 부서 명을 'all' 로 변경하였습니다.
=> feat #10 - [캘린더] 부서 선택 셀렉트박스 추가

src/pages/departmentAndposition/DepartPeopleModal.js, src/pages/departmentAndposition/DepartRegistModal.js, src/pages/departmentAndposition/PositionPeopleModal.js, src/pages/departmentAndposition/PositionRegisterModal.js, src/pages/departmentAndposition/departmentAndPosition.js
- 부서 및 직급 명을 누르면 해당 구성원들의 리스트를 모달창으로 출력
- 직급 삭제하는데 인원수가 존재하지 않아 삭제하는데 불편함이 있어 인원수를 보여줄 수 있는 기능 추가
- 부서 및 직급 input box style 수정
=> 직급 인원수 컬럼 추기, 부서 및 직급명을 누르면 해당 구성원의 정보 출력

src/apis/CommuteAPICalls.js, src/components/commutes/CommuteCalendar.js, src/components/commutes/CommuteDay.js, src/components/commutes/CommuteItem.js, src/components/commutes/CommuteListByMember.js, src/components/commutes/CommuteMonth.js, src/components/commutes/CommuteRow.js, src/components/commutes/InsertCorrectionModal.js, src/modules/CommuteModule.js, src/pages/commute/CommuteManage.js, src/pages/commute/RecordCommute.js, src/pages/commute/RecordCorrectionOfCommute.js, src/utils/CommuteUtil.js
=> feat #17 - [출퇴근] 부서별 출퇴근 내역 조회

src/pages/calendar/Calendar.js, src/utils/leaveUtil.js
> 전체 보기를 추가하여 모든 부서의 일정을 조회할 수 있는 로직을 추가하였습니다.
=> feat #11 - [캘린더] 부서 선택 셀렉트 박스에 전체 추가

src/common/common.js, src/components/Header.js, src/components/commutes/CommuteCalendar.js, src/components/commutes/CommuteDay.js, src/components/commutes/CommuteMonth.js, src/components/commutes/CommuteRow.js, src/components/commutes/CorrectionManageItem.js, src/css/commute/commute.css, src/pages/Main.js, src/pages/commute/CommuteCorrectionManage.js, src/pages/commute/CommuteManage.js, src/pages/commute/commute.css
=> feat #18 - [출퇴근] 부서별 출퇴근 내역 조회

package-lock.json, package.json, src/apis/CommuteAPICalls.js, src/common/common.js, src/components/commutes/CorrectionDetailModal.js, src/components/commutes/CorrectionItem.js, src/pages/commute/RecordCorrectionOfCommute.js
- 로그인한 멤버가 본인의 출퇴근 정정 요청한 내역을 확인할 수 있습니다.
- 렌더링 이슈로 수정하였습니다.
- 최초 렌더링 시 조회 당일 기준 달의 내역을 조회합니다. 
- 상단 날짜를 선택하여 최대 12개월의 정정 내역을 조회할 수 있습니다.
=> feat #12 - [출퇴근] 멤버별 출퇴근 정정 내역 조회

src/apis/InsiteAPICalls.js, src/modules/InsiteModule.js, src/pages/Main.js, src/pages/insite/Insite.js
> 금일 휴가자 + 금일 출근자 통계 합치기 -> 금일 출근 여부를 휴가와 함께 보여줌으로써 더욱 통계치 확실히 하기 위함.
> 휴가 출근의 합침으로 인한 new 통계, 구성원 생년월일이 추가된 것을 통한 월별 생일자 / 금주 생일자 / 금일 생일자 표시
=> feat #4 - [통계] 전체적인 리팩토링

package-lock.json, package.json, src/components/commutes/ClockInModal.js, src/components/commutes/ClockLimitModal.js, src/components/commutes/ClockOutModal.js, src/components/commutes/CommuteTime.js, src/components/commutes/InsertCorrectionModal.js, src/pages/commute/RecordCommute.js
출근시간/ 퇴근시간 등록 후, 즉시 재등록 시도 시 제한이 걸리지만 리렌더링 후에는 재등록 되는 이슈 발생하여
각각의 기능을 수행할 모달을 분리하여 해결하였습니다.
=> fix #18 - [출퇴근] 출근시간/ 퇴근시간 등록 시 중복 입력되는 오류

src/components/commutes/ClockOutModal.js, src/components/commutes/CommuteListByMember.js, src/components/commutes/InsertCorrectionModal.js, src/pages/commute/RecordCommute.js
퇴근시간 등록 시, 총 근무 시간 계산하는 로직 추가하였습니다.
=> feat #19 - [출퇴근] 퇴근 시간 등록 시, 총 근무 시간 계산 로직 추가

src/apis/CommuteAPICalls.js, src/components/commutes/CommuteItem.js, src/components/commutes/CommuteListByMember.js, src/components/commutes/CorrectionManageItem.js, src/components/commutes/CorrectionUpdateModal.js, src/components/commutes/InsertCorrectionModal.js, src/pages/commute/CommuteCorrectionManage.js, src/pages/commute/CommuteManage.js, src/pages/commute/RecordCorrectionOfCommute.js
role이 ADMIN인 멤버가 전체 출퇴근 정정 내역을 조회하고 상세 조회할 수 있는 기능입니다.
=> feat #20 - [출퇴근] 전체 출퇴근 정정 내역 조회/ 상세 조회

src/apis/ChattingAPICalls.js, src/components/Header.js, src/css/announce/ancDetail.css, src/modules/CahttingModules.js, src/pages/Main.js, src/pages/announce/AnnounceDetail.js, src/pages/announce/Announces.js, src/pages/announce/InsertAnnounce.js, src/pages/announce/UpdateAnnounce.js, src/pages/chatting/Room.js, src/pages/chatting/RoomList.js, src/pages/insite/Insite.js, src/pages/note/ReceiveNoteList.js, src/pages/note/SendNoteList.js
=> feat #7 - [채팅] 채팅 메시지 저장 / 기존 메시지 불러오기

src/css/leave/LeaveAccrual.css, src/css/leave/LeaveCheckModal.css, src/css/leave/MyLeaveModal.css, src/pages/leave/LeaveAccrualModal.js, src/pages/leave/LeaveCheckModal.js, src/pages/leave/LeaveProcessingModal.js, src/pages/leave/MyLeave.js, src/pages/leave/MyLeaveModal.js, src/utils/leaveUtil.js
> 처리나 등록 등의 행위에 대해서 사용자에게 한 번 더 묻는 모달을 추가하였습니다.
> 발생 관리에서 멤버 목록을 조회해올 때 로딩 기능이 굳이 필요 없을 거 같아 제거하였습니다.
> 발생 사유가 길면 ...으로 생략되어 보이게 css를 추가하였습니다.
=> feat #16 - [휴가] 확인 모달 추가 및 리팩토링

package-lock.json, package.json, src/components/approvals/TempSaveModal.js, src/css/approval/ApprovalInsert.module.css, src/css/approval/TempSaveModal.module.css, src/pages/approval/ApprovalInsert.js
=> feat#5 전자결재 임시저장

src/apis/CommuteAPICalls.js, src/components/commutes/ClockInModal.js, src/components/commutes/ClockOutModal.js, src/components/commutes/CommuteItem.js, src/components/commutes/CommuteListByMember.js, src/components/commutes/CorrectionDetailModal.js, src/components/commutes/CorrectionManageItem.js, src/components/commutes/CorrectionUpdateModal.js, src/components/commutes/InsertCorrectionModal.js, src/pages/commute/CommuteCorrectionManage.js, src/pages/commute/CommuteManage.js, src/pages/commute/RecordCommute.js, src/pages/commute/RecordCorrectionOfCommute.js
출퇴근 등록, 정정 처리 시 내역 조회 API 재호출하는 기능 추가
selectBox 화면 스크롤 시 이동하는 이슈 해결
=> fix #21 - [출퇴근] 출퇴근 등록, 정정 처리 시 내역 조회 API 재호출하는 기능 추가

package-lock.json, package.json, src/modules/ApprovalReducer.js, src/pages/approval/ApprovalInsert.js
=> Feat#6 전자결재 재임시저장

src/pages/announce/InsertAnnounce.js
>공지사항 파일등록 갯수 제한
>제한 갯수 넘어가면 등록된 파일 초기화
=> refactor #7 - 공지사항 파일 등록 갯수 제한

src/components/commutes/TotalWorkingHours.js, src/pages/commute/CommuteManage.js
부서별 전체 출퇴근 내역 조회에서 근무 시간 조회 기능을 추가하였습니다.
=> feat #22 - [출퇴근] 부서별 전체 출퇴근 내역 조회에서 근무 시간 조회 기능 추가

src/pages/approval/ApprovalInsert.js
=> fix#1 전자결재 재임시저장 수정

src/App.js, src/apis/ApprovalAPI.js, src/components/approvals/ApprovalListComponent.js, src/components/approvals/ApproversInfo.js, src/components/approvals/ReferencerComponent.js, src/css/approval/ApprovalDetail.module.css, src/css/approval/ApproversInfo.module.css, src/css/approval/ReferencerComponent.module.css, src/modules/ApprovalReducer.js, src/pages/approval/ApprovalDetail.js
=> feat#8 전자결재 상세조회 페이지 구현

src/apis/ChattingAPICalls.js, src/modules/CahttingModules.js, src/pages/chatting/JoinRoom.js, src/pages/chatting/Room.js, src/pages/chatting/RoomList.js
방을 삭제하면 양쪽 전부 삭제 됐었던 로직에서 -> 삭제여부 컬럼을 추가하여, 한쪽에서만 보여지지 않도록 수정
=> feat #8 - [채팅] 채팅방 삭제 -> delete : put 변경

src/pages/calendar/CalendarModal.js, src/pages/calendar/CalendarUpdateModal.js
> 종료일 선택 시 최솟값을 시작일시로 지정하여 시작일 이전 일시는 선택할 수 없게 구현했습니다.
> 만약 수정을 통해 시작 일시가 종료 일시 이후로 선택되거나 종료 일시가 시작 일시 이후로 선택된다면 종료 일시를 초기화하도록 구현하였습니다.
=> feat #12 - [캘린더] 일정 선택 시 유효성 검사 추가

src/pages/chatting/JoinRoom.js, src/pages/chatting/Room.js, src/pages/chatting/RoomList.js
memberList 이미 존재하는 방일 시, memberList에서 제외
=> fix #9 - [채팅] 채팅방 생성: memberList 이미 존재하는 방일 시, memberList에서 제외

src/css/leave/LeaveAccrualModal.css, src/css/leave/LeaveCheckModal.css, src/css/leave/MyLeaveModal.css, src/pages/leave/LeaveAccrualModal.js, src/pages/leave/LeaveCheckModal.js, src/pages/leave/LeaveProcessingModal.js, src/pages/leave/MyLeave.js, src/pages/leave/MyLeaveModal.js
> 휴가 신청 시 일자 선택의 최솟값을 당일 일자로 지정하여 당일 이전의 일자는 선택할 수 없게 막아두었습니다.
> 휴가 시작일을 선택했다면 종료일의 최솟값은 시작일이 되도록 구현하여 종료일은 시작일 이전 일자를 선택할 수 없도록 하였습니다.
> 종료일은 시작일로부터 잔여 휴가 일수만큼만 선택할 수 있게 구현하였습니다.
> 반차 선택 시 종료일을 시작일로 고정되게 구현하였습니다.
> 시작일을 종료일 이후로 선택할 경우 종료일의 값이 초기화 되도록 구현하였습니다.
> 발생 등록 시 미입력된 필드가 있다면 알럿 창을 통해 메시지를 표기하고 처리가 진행되지 않게 구현하였습니다.
> 발생 등록 처리 전 등록 여부를 재확인하는 모달창을 추가하였습니다.
> 발생 일수에 음수가 입력될 경우 알럿 창을 통해 메시지를 표기합니다.
> 휴가 처리 시 반려의 경우 반려 사유를 입력하지 않았다면 알럿 창을 통해 메시지를 표기합니다.
=> feat #17 - [휴가] 휴가 관련 리팩토링

src/components/commutes/CommuteItem.js, src/components/commutes/CommuteListByMember.js, src/components/commutes/NewCommuteAndCorrection.js, src/pages/commute/CommuteCorrectionManage.js, src/pages/commute/CommuteManage.js, src/pages/commute/RecordCorrectionOfCommute.js
출퇴근 내역이 없을 때 출퇴근 정정 등록 시, 처리하는 로직 추가하였습니다.
=> feat #23 - [출퇴근] 출퇴근 내역이 없을 때 출퇴근 정정 등록 시, 처리하는 로직

src/components/approvals/TinyEditor.js, src/css/approval/ApprovalDetail.module.css, src/css/approval/TempSaveModal.module.css, src/css/approval/WarningModal.module.css, src/pages/approval/ApprovalDetail.js
=> feat #10 전자결재 처리

package-lock.json, package.json, src/components/commutes/AddWorkTimeModalBy8.js, src/components/commutes/ClockInModal.js, src/components/commutes/ClockOutModal.js, src/components/commutes/ClockOutWarningModalBy52.js, src/components/commutes/CommuteItem.js, src/components/commutes/CommuteListByMember.js, src/components/commutes/LimitClockInModalBy52.js, src/components/commutes/NewCommuteAndCorrection.js, src/css/commute/commute.css, src/css/member/memberPage.css, src/modules/CommuteModule.js, src/pages/commute/CommuteManage.js, src/pages/commute/RecordCommute.js
부서별 출퇴근 내역 조회 렌더링 시 오류 수정하였습니다.
=> fix #23 - [출퇴근] 부서별 출퇴근 내역 조회 렌더링 시 오류 수정

src/apis/InsiteAPICalls.js, src/common/ApprovalCounts.js, src/common/ApproverCounts.js, src/common/MyLeaveCounts.js, src/pages/Main.js, src/pages/chatting/Room.js
기존엔 전체 미처리 상신건수를 보여줬지만, 수정하여 결재선에 따라 숫자가 보여지도록 수정
=> feat #6 - [통계] 메인페이지 상신인 조건 추가

src/apis/ApprovalAPI.js, src/css/approval/ApprovalDetail.module.css, src/pages/approval/ApprovalDetail.js
=> feat#10 전자결재 파일 다운로드

src/App.js, src/apis/CommuteAPICalls.js, src/apis/NoticeAPICalls.js, src/components/Header.js, src/components/commutes/AddWorkTimeModalBy8.js, src/components/commutes/ClockInModal.js, src/components/commutes/ClockLimitModal.js, src/components/commutes/ClockOutModal.js, src/components/commutes/ClockOutWarningModalBy52.js, src/components/commutes/CommuteItem.js, src/components/commutes/CorrectionDetailModal.js, src/components/commutes/CorrectionUpdateModal.js, src/components/commutes/InsertCorrectionModal.js, src/components/commutes/NewCommuteAndCorrection.js, src/css/commute/commute.css, src/css/main.css, src/css/member/manageMember.css, src/css/member/profile.css, src/css/member/setMember.css, src/modules/CommuteModule.js, src/pages/commute/CommuteCorrectionManage.js, src/pages/commute/RecordCommute.js, src/pages/commute/RecordCorrectionOfCommute.js, src/pages/profile/HistoryInfo.js, src/style.css
=> style #2 [버튼] 버튼 / hover 공통 색상으로 수정

package-lock.json, package.json, src/App.js, src/apis/CommonAPI.js, src/common/common.js, src/components/Header.js, src/components/Sidebar.js, src/components/commutes/ClockInModal.js, src/components/commutes/ClockLimitModal.js, src/components/commutes/ClockOutModal.js, src/components/commutes/CommuteItem.js, src/components/commutes/CorrectionDetailModal.js, src/components/commutes/CorrectionUpdateModal.js, src/components/commutes/InsertCorrectionModal.js, src/components/commutes/NewCommuteAndCorrection.js, src/css/commute/commute.css
사이드탭 권한별로 조건부 렌더링 추가하였습니다.
버튼 css 공통 스타일로 변경하고 hover 추가하였습니다.
=> feat #24 - [출퇴근] 사이드탭 권한별 조건부 렌더링 및 버튼 css 스타일 변경

src/css/common.css, src/pages/calendar/Calendar.js, src/pages/calendar/CalendarModal.js, src/pages/calendar/CalendarUpdateModal.js, src/pages/leave/LeaveAccrualModal.js, src/pages/leave/LeaveCheckModal.js, src/pages/leave/LeaveProcessingModal.js, src/pages/leave/Leaves.js, src/pages/leave/MyLeaveModal.js, src/pages/survey/SurveyInsertModal.js, src/pages/survey/SurveyList.js, src/pages/survey/SurveyModal.js
> common.css 파일에 공통 버튼 css 를 작성하였습니다
> 휴가, 캘린더, 수요조사에 사용된 버튼의 클래스 네임을 해당 공통 버튼 클래스네임으로 변경하였습니다.
=> style #2 [버튼] - 공통 버튼 css 추가

src/css/common.css, src/css/leave/LeaveAccrual.css, src/css/leave/MyLeave.css, src/css/survey/SurveyList.css, src/pages/leave/LeaveAccrual.js, src/pages/leave/MyLeave.js
> 컨텐츠 헤더 버튼에 대한 공통 css를 common.css에 추가하였습니다.
=> style #3 [버튼] - 공통 컨텐츠 헤더 버튼 css 추가

src/css/common.css, src/pages/proposal/AdminProposalPage.js, src/pages/proposal/ProposalPage.js
=> fix # 26 - [공통] 오류 수정

src/components/commutes/CommuteTime.js, src/pages/commute/CommuteManage.js
=> feat #27 - [출퇴근] 부서 수정
